#!/usr/bin/env bash

declare devcontainer_id

# devcontainer_id="$(docker ps --format 'json' | jq -r '. | select(.Names | contains("nix-workspace")) | select(.Image == "nixos/nix:latest") | .ID')"
devcontainer_id="$(docker ps --all --format 'json' | jq -r '. | select(.Names | contains("nix-workspace")) | .ID')"

./.devcontainer/scripts/dc-list
printf "\n"

# stop old container
if [[ -n ${devcontainer_id} ]]; then
	printf "Stopping container...\n"
	echo Running: docker stop "${devcontainer_id}"
	docker stop "${devcontainer_id}"
	printf "done.\n"
fi
printf "\n"
